.TH LCLIB "28 March 1995" "LCLIB"
.SH NAME
Lclib \- Libraries for studies of Linear Collider Physics.
.SH DESCRIPTION
Lclib is a collection of programs for Linear Collider Physics
studies. The files are in 
.B
/proj/phys/lclib/95a

Diretories are organized as follows.
.RS
.I
.B bin
Commands
.br
.I 
.B doc
Documents
.br
.I
.B examples
Various examples
.br
.I
.B gen
Programs for event generations, those available in HEP market.
.br
.I
.B lib
Archived libraries
.br
.I
.B man
Files for man command
.br
.I
.B simjlc
Simple detector simulator for JLC Physics study.
.br
.I
.B util
Utilites for physics study.
.RE

Documents for these files may be found under
.B doc
or
.B man


.SH "See Also"
rn_lclib(1), rn_include(1), exp2inc(1), Release95a(5)

.SH Files
/proj/phys/lclib/95a/Release95a.ps

.SH Author
Akiya Miyamoto, Physics Department, KEK,
E\-mail:miyamoto@kekux1.kek.jp


       


       

