C***********************************************************************
C*
C* Common /EVTPRM/
C*
C***********************************************************************
C*
      REAL*8 RS, EMINS, EPLUS, EBEAM, XG(10)
      COMMON /EVTPRM/ RS, EMINS, EPLUS, EBEAM, XG
C*
C*   RS  ; Collision energy
C*   EMINS ; Electron energy at collision.
C*   EPLUS ; Positron energy at collision.
C*   EBEAM ; Beam energy.
C*
C   XG(1)  : Cos(th) of u
C     (2)  ; Phi of u
C

