C**********************************************************************
C*
C*  Common /EWPARM/
C*
C*  Parameters for Standard Electro-Weak interactions.
C*
C**********************************************************************
C
      REAL*8          c_$PI, c_$2PI, c_$HPI, c_$ALPHA, c_$CONV,       
     >                c_$SN2TW, c_$AMZ, c_$AMZ2, c_$GAMZ, c_$AMW, c_$A
     . MW2, c_$GAMW,       
     >                c_$ALAM,  c_$ALFAS  
C
      COMMON /EWPARM/ c_$PI, c_$2PI, c_$HPI, c_$ALPHA, c_$CONV,       
     >                c_$SN2TW, c_$AMZ, c_$AMZ2, c_$GAMZ, c_$AMW, c_$A
     . MW2, c_$GAMW,       
     >                c_$ALAM,  c_$ALFAS  
C
