C***********************************************************************
C*                                                                      
C*   Common /SPDATA/                                                    
C*                                                                      
C*                                                                      
C***********************************************************************
C*                                                                      
      INTEGER*4        IDPART                                           
      REAL*4           CHARGE                                           
      COMMON /SPDATA/  IDPART, CHARGE                                   
C   IDPART : Parton ID to be generated.                                 
C   CHAGRE : Charge of parton.                                          
