C   12/11/86 611122115  MEMBER NAME  SCREEN   (FORT)     M  FORTRAN
CMSP       SUBROUTINE CM$CLR
      SUBROUTINE CMxCLR
      RETURN
C
CMSP       ENTRY CM$HOM
      ENTRY CMxHOM
      RETURN
      END
