C*  /TBSBUF/                                                           *
C*    PARAMETER       (NSIZE = 10000)                                  *
C*    PARAMETER       (MSIZE = 2*NSIZE)                                *
C*    COMMON /TBSBUF/ IBUFF(NSIZE)                                     *
C*    INTEGER*2       HBUFF(MSIZE)                                     *
C*    EQUIVALENCE     (IBUFF(1),HBUFF(1))                              *
