#!/bin/csh
# **********************************************************
#
#  Example of script for event generation using BASES V5.1
#
#  Coded by A.Miyamoto   19-Oct-1994
#
# *********************************************************
#

set dir=.
set program=$dir/wwanal.ex
set lchome=/proj/phys/lclib/pro
date

#
# ==============================================================
# ==============================================================
# First run: Do BASES, then SPRING and event generation.
# ==============================================================
# ==============================================================
#
nice $program << eof 
@!                                                                      
@!*************************************************                     
@! Input section for Steering part.                                     
@!*************************************************                     
@!                                                                      
STEERING                                                                
@!   EVENT GEN(400000)     ! Number of event is just a dummy.
   STEERING DEBUG(3)  ! Standard debug level.
   INPUT FILE(BASES.WW.TBS)   ! Output file for BASES data
   EVENT GEN(500)     ! Number of event is just a dummy.
*   ANAL SEQ(BASES LUND )
   ANAL SEQ(BASES LUND SWIMMER SMEARING USER)
EXIT                                                                    
@!                                                                      
@!*************************************************                     
@! Input section for Spring part.                                       
@!*************************************************                     
@!                                                                      
BASES
  HELP    !  for PRINT command help
  GETB 1  !  Get  BASES data from TBS Bank
  PUTB 0  !  BASES results are not written to the bank.
  DOSP 1  !  Run spring. 
  PHST 0  !  Does not print BASES HIST
EXIT                                                                 
@!
@!                                                                      
@!                                                                      
@!*************************************************                     
@! Input section for Lund hadronizer. (LUND63)         
@!*************************************************                     
@!                                                                      
LUND_FRAG                                                               
@! PAR 12 0.355       ! sigmaq --                                   
@!  310.361           ! a       ! fragmentation parameters tuned using  
@!  32 0.914          ! b      --       EXP4 hadronic events           
@! E 21 0.378         ! lambda -- Lambda for LLA tuned using EXP4 evts 
EXIT                                                                    
@!                                                                      
@!*************************************************                     
@! Swimmer                                                              
@!*************************************************                     
@!                                                                      
Swimmer:                                                                
@$lchome/simjlc/param/swimer4.com     ! Standard swimer parameters.
0                             ! End of input                          
EXIT                                                                    
@!                                                                      
@!*************************************************                     
@! Smearing parameters.                                                 
@!*************************************************                     
@!                                                                      
Smearing:                                                               
@#lchome/simjlc/param/detect4.com ! Standard swimer parameters
0                             ! End of input                          
EXIT                                                                    
@!
@!                                                                      
@!*************************************************                     
@! Input section for USER routine.                                      
@!*************************************************                     
@!                                                                      
USER
dis.wwanl                                                                 
EXIT                                                                 
@!                                                                      
@!*************************************************                     
@! Start execution.                                                     
@!*************************************************                     
@!                                                                      
GO                                                                      
eof

date

echo "End of job."

