C*********************************************************************
C*
C*  Pointers to the version # data in the RUNLIST data base.
C*
C*********************************************************************
C
      PARAMETER    (IRxIDC = 41,     IPxIDC = 51,
     >              IRxTPC = 42,     IPxTPC = 52,
     >              IRxBTO = 43,     IPxBTO = 53,
     >              IRxBDC = 44,     IPxBDC = 54,
     >              IRxBCL = 45,     IPxBCL = 55,
     >              IRxBMU = 46,     IPxBMU = 56,
     >              IRxEDC = 47,     IPxEDC = 57,
     >              IRxECL = 48,     IPxECL = 58,
     >              IRxLUM = 49,     IPxLUM = 59,
     >              IRxFLT = 50,     IPxSTR = 60 )
C
