C***********************************************************************
C*
C*  Common for Beam Data DST production
C*
C***********************************************************************
C*
      CHARACTER*80    DSTINF(3)
      COMMON /PRDSTC/ DSTINF
      COMMON /PRDSTR/ DSTSIZ
C*
C*  DSTINF  ; DST information passed from SUBDST JOB.
C*  DSTSIZ  ; Total data size in unit of feet. CTL tape.
C*
C*
