C**********************************************************************
C*
C* ---------------
C* Parameter  @PRDTPT
C* ---------------
C*
C*   Pointers to each detector module.
C*   Corresponds to the index to NJBDBG and NJBLVL.
C*
C**********************************************************************
C*
      PARAMETER ( LxREDC = 1,
     .            LxPROD = 2,
     .            LxSIML = 3 )
C
      PARAMETER ( LxSTR1 = 1,
     .            LxSTR2 = 2,
     .            LxIDC  = 6,   LxTPC = 7, LxBTOF = 8,
     .            LxBDC  = 9,   LxBCL =10, LxBMU  = 11,
     .            LxETOF =12,   LxEDC =13, LxECL  = 14,
     .            LxLUM  =15,   LxNEW =16, LxHTRK = 17,
     .            LxHNEU =18,   LxHFLT=19, LxUSER = 20 )
C*
