CC********************************************************************CC
C*                                                                    *C
C*=================                                                   *C
C*   / PRETYP /                                                       *C
C*=================                                                   *C
C*                                                                    *C
C* 1) Contents                                                        *C
C*     Event type and FIlter ID information.
C*                                                                    *C
C* 2) Update Record                                                   *C
C*    05/06/87  A. Miyamoto  Original Version.                        *C
C*                                                                    *C
CC********************************************************************CC
 
      COMMON /PRETYP/ IDFILT, IDEVNT
C
C     IDFILT  : Filter ID.
C     IDEVNT  : Event ID.
C
C=    IDFILT /0/
C=    IDEVNT /0/
