C   14/02/88 802141214  MEMBER NAME  #TVCOMM  (FORT)     M  FORTRAN     00000000
C                                                                               
C  WHEN MODIFY THIS COMMON, COMPILE THE FOLLOWING MEMBERS.                      
C     'T#TP.DISPLAY.FORT(BLOCKD)'                                               
C     'T#TP.CLI.FORT(TVPACK)'                                                   
C                                                                               
      COMMON /TVCOMM/ AREA(2,2),WINDOW(2,2),                                    
     &                I1,I2,IFONT,TSIZE,IFLUSH,                                 
     &                ASPECT(2),WDOWSZ(2,2)                                     
C                                                                               
