C   24/06/87 706241651  MEMBER NAME  FDPRD    (FORT)     M  FORTRAN
C
C THIS MODULE IS MACHINE DEPENDENT
C
       SUBROUTINE FDPRD( QUEST,VALUE )
C
       CHARACTER QUEST*(*), K*1, ANSWER*16
       REAL*8 VALUE, MINI, MAXI
       REAL*8 F
C
C..... CHANGE REAL*8 FLOATING
C
       I3 = 2
       GOTO 1
C
       ENTRY FDPRDL( QUEST,VALUE,MINI,MAXI )
C
       I3 = 4
       GOTO 1
C
1      CONTINUE
C
       IF (QUEST(1:1).EQ.'?') VALUE = 0.0D0
       IF (I3.GE.3) VALUE = MAX(MINI,VALUE)
       IF (I3.GE.4) VALUE = MIN(MAXI,VALUE)
       WRITE (ANSWER,101) VALUE
101    FORMAT (1PG16.6)
       IF (ANSWER(12:16).EQ.'0E+00') ANSWER(12:16) = ' '
3      CALL ARGRD(QUEST,ANSWER)
       F = VALUE
       CALL NUMRD(F,10,K)
       IF (K.EQ.'\\') GOTO 3
       VALUE = F
       IF (I3.GE.3) VALUE = MAX(MINI,VALUE)
       IF (I3.GE.4) VALUE = MIN(MAXI,VALUE)
C      CALL SET_NO_HELP
       RETURN
       END
