C   17/06/86 712222255  MEMBER NAME  FLTRD    (FORT)     M  FORTRAN
C
C THIS MODULE IS MACHINE DEPENDENT.
C
       SUBROUTINE FLTRD(QUEST,VALUE)
C
       CHARACTER QUEST*(*), K*1, ANSWER*16
       REAL*4 VALUE, MINIM, MAXIM
       REAL*8 F
C
C..... CHANGE REAL*4 FLOATING
C
       I3 = 2
       GOTO 1
C
       ENTRY FLTRDL(QUEST,VALUE,MINIM,MAXIM)
C
       I3 = 4
       GOTO 1

1      CONTINUE
C
       IF (QUEST(1:1).EQ.'?') VALUE = 0
       IF (I3.GE.3) VALUE = MAX(MINIM,VALUE)
       IF (I3.GE.4) VALUE = MIN(MAXIM,VALUE)
       WRITE (ANSWER,101) VALUE
101    FORMAT (1PG16.6)
       IF (ANSWER(12:16).EQ.'0E+00') ANSWER(12:16) = ' '
3      CALL ARGRD(QUEST,ANSWER)
       F = VALUE
       CALL NUMRD(F,10,K)
       IF (K.EQ.'\\') GOTO 3
       VALUE = F
       IF (I3.GE.3) VALUE = MAX(MINIM,VALUE)
       IF (I3.GE.4) VALUE = MIN(MAXIM,VALUE)
       RETURN
       END
