C   03/07/85 705301408  MEMBER NAME  INTRD    (FORT)     M  FORTRAN
C
C THIS MODULE IS MACHINE DEPENDENT
C
       SUBROUTINE INTRD( QUEST,VALUE )
C
       CHARACTER QUEST*(*), K*1, ANSWER*16
       INTEGER*4 VALUE, MINIM, MAXIM
       REAL*8 F
C
C..... CHANGE INTEGER
C
       I3 = 2
       GOTO 1
C
       ENTRY INTRDL( QUEST,VALUE,MINIM,MAXIM )
C
       I3 = 4
       GOTO 1
C
1      CONTINUE
C
       IF( QUEST(1:1).EQ.'?' ) VALUE = 0
       IF( I3.GE.3 ) VALUE = MAX( MINIM,VALUE )
       IF( I3.GE.4 ) VALUE = MIN( MAXIM,VALUE )
       WRITE ( ANSWER,101 ) VALUE
101    FORMAT (I16)
3      CALL ARGRD(QUEST,ANSWER)
       F = VALUE
       CALL NUMRD(F,10,K)
       IF (K.EQ.'\\') GOTO 3
       VALUE = MIN(MAX(-2147483648.D0,F),2147483647.D0)
       IF (I3.GE.3) VALUE = MAX(MINIM,VALUE)
       IF (I3.GE.4) VALUE = MIN(MAXIM,VALUE)
       RETURN
       END
