C   04/09/87 709041713  MEMBER NAME  TVWRTL   (FORT)     M  FORTRAN
C
      SUBROUTINE TVWRTL( MODE,IROW,ICOL,BUFFER )
C
C ARG
      CHARACTER * (*)  MODE,BUFFER
      INTEGER   *  4   IROW,ICOL
C
C CONST
      INTEGER * 4  BUFSIZ
      PARAMETER( BUFSIZ = 2000 )
C
C VAR
      CHARACTER * (BUFSIZ)  TVBUF
C
C BEGIN
      CALL TVPUTL( 'WCC',TVBUF,LTVBUF )
      CALL TVPUTL( MODE,TVBUF,LTVBUF,IROW,ICOL,BUFFER )
      CALL TVPUTL( 'PUT',TVBUF,LTVBUF )
C
      RETURN
      END
