.TH RN_INCLUDE 1 "20 March 1995" "RN_INCLUDE"
.SH NAME
rn_include \- Modify INCLUDE statement.
.SH SYNOPSIS
.B rn_include
.SH DESCRIPTION
This command modifies FORTRAN's INCLUDE statements 
so that to meet lclib standard, namely, convert a file name
to lower case and removes a character _ prefixed to the file name.
.SH FILES
.br
.TP
/proj/phys/lclib/95a/bin/rn_include
.TP
/proj/phys/lclib/95a/man
.SH "SEE ALSO"
Release_Note(5)
.SH AUTHORS
Akiya Miyamoto, Physics Department, KEK.
E\-mail:miyamoto@kekux1.kek.jp



