C
      COMMON /SMRCLP/ CLSPAR(5,4)
C
C  /SMRCLP/ Parameter for Clustering.
C           CLSPAR(i,1) ; For Barrel EMC
C                 (i,2) ; For EndCap EMC
C                 (i,3) ; For Barrel HDC
C                 (i,4) ; For EndCap HDC
C*
C=    DATA (CLSPAR(I,1),I=1,5)/ 100., 0.40, 0.20, 1.00, 0.3 /
C=    DATA (CLSPAR(I,2),I=1,5)/ 100., 0.40, 0.20, 1.00, 0.3 /
C=    DATA (CLSPAR(I,3),I=1,5)/ 100., 0.40, 0.20, 1.00, 0.25 /
C=    DATA (CLSPAR(I,4),I=1,5)/ 100., 0.40, 0.20, 1.00, 0.25 /
