      COMMON /SMREGO/ NPHIEM, NTHTEM, NRADEM,         DPHIEM, DTHTEM,
     .                DRDMEM, DRDPEM, THMNEM, THMXEM, RMMNEM, RMMXEM,
     .                RPMNEM, RPMXEM, RCYEM(2), ZCYEM(2), NPADEM
      INTEGER*4       NPHIEM, NTHTEM, NRADEM, NPADEM
      REAL   *4       DPHIEM, DTHTEM, DRDMEM, DRDPEM, THMNEM, THMXEM,
     .                RMMNEM, RMMXEM, RPMNEM, RPMXEM, RCYEM, ZCYEM
C=    DATA    NPHIEM /  156  /
C=    DATA    NTHTEM /   50  /
C=    DATA    NRADEM /   18  /
C=    DATA    NPADEM /   10  /
C=    DATA    DPHIEM /    0. /
C=    DATA    DTHTEM /    0. /
C=    DATA    DRDMEM /    0. /
C=    DATA    DRDPEM /    0. /
C=    DATA    THMNEM /    0. /
C=    DATA    THMXEM /    0. /
C=    DATA    RMMNEM /    0. /
C=    DATA    RMMXEM /    0. /
C=    DATA    RPMNEM /    0. /
C=    DATA    RPMXEM /    0. /
C=    DATA    RCYEM  /   45., 250. /
C=    DATA    ZCYEM  / -300., 300. /
