      COMMON /SMRHGO/ NPHIHD, NTHTHD, NRADHD, DPHIHD, DTHTHD, DRDMHD,
     .                DRDPHD, THMNHD, THMXHD, RMMNHD, RMMXHD,
     .                RPMNHD, RPMXHD, RCYHD(2), ZCYHD(2)
      INTEGER*4       NPHIHD, NTHTHD, NRADHD
      REAL   *4       DPHIHD, DTHTHD, DRDMHD, DRDPHD, THMNHD, THMXHD,
     .                RMMNHD, RMMXHD, RPMNHD, RPMXHD, RCYHD, ZCYHD
C=    DATA    NPHIHD /   78  /
C=    DATA    NTHTHD /   25  /
C=    DATA    NRADHD /    9  /
C=    DATA    DPHIHD /    0. /
C=    DATA    DTHTHD /    0. /
C=    DATA    DRDMHD /    0. /
C=    DATA    DRDPHD /    0. /
C=    DATA    THMNHD /    0. /
C=    DATA    THMXHD /    0. /
C=    DATA    RMMNHD /    0. /
C=    DATA    RMMXHD /    0. /
C=    DATA    RPMNHD /    0. /
C=    DATA    RPMXHD /    0. /
C=    DATA    RCYHD  /  48.0, 270. /
C=    DATA    ZCYHD  / -324., 324. /
