# -----------------------------------------------
# Makefile to create FORTLIB library
#
# (Author) Akiya Miyamoto, KEK, 15-Jan-2003
#          Recoded so as not to use Imakefile
#$Id$
# -----------------------------------------------

include $(LCLIBROOT)/config/Makefile.lclib

OBJS =   dcgsm.o dcsgm.o dseig1.o hoqrvd.o hqriid.o

# -------------------------------------------------

all: $(OBJS)

install:

# -------------------------------------------------

include $(LCLIBROOT)/config/Makefile.defaults